# from https://pre-commit.com/
exclude: ^(.venv*|spikes*)
# specific hooks defined under repos
repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix, --select, I]
    # Run the formatter.
    - id: ruff-format
